source "https://rubygems.org"

group :development, :test do
  gem 'debugger', :require => false
  gem 'mocha', :require => false

  gem 'autotest-standalone'
  gem 'autotest-growl'
  gem 'autotest-fsevent' if RUBY_PLATFORM =~ /darwin/i
  gem 'rb-fsevent', :require => false if RUBY_PLATFORM =~ /darwin/i

  
end